2025-08-02 11:51:34,018 - ERROR - Необработанное исключение: IndexError: list index out of range
2025-08-02 11:51:34,019 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 3666, in tool_page
    page()
    ~~~~^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 3728, in page
    fill_table(player_list)  # заполняет TableWidget списком игроков
    ~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\Alex\Competitions_TT_v1.1\main.py", line 2697, in fill_table
    coach_id = str(list(player_selected[row].values())[num_columns[7]])
                                                       ~~~~~~~~~~~^^^
IndexError: list index out of range
