2025-08-01 12:21:59,974 - ERROR - Необработанное исключение: AttributeError: 'MainWindow' object has no attribute 'listWidget_1'
2025-08-01 12:21:59,984 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v6\main.py", line 3429, in dclick_in_listwidget
    my_win.listWidget_1.clear()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'listWidget_1'
2025-08-01 12:22:12,325 - ERROR - Необработанное исключение: AttributeError: 'MainWindow' object has no attribute 'listWidget_1'
2025-08-01 12:22:12,332 - ERROR - Трассировка стека:
Traceback (most recent call last):
  File "c:\Users\Alex\Competitions_TT_v6\main.py", line 3429, in dclick_in_listwidget
    my_win.listWidget_1.clear()
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'listWidget_1'
